### ISSUE TITLE
Intercoms

### ISSUE THREAD

**Issue by pergolafabio** [surfzoid/HikRtsp#1]
Hi, just found your project... I have build a project for Hikvision doorbells to intercept events... Based on the SDK...

I believe you found the arm64 lib on my GitHub page :-) that you  use for the player

Anyway, do you also have intercoms? My goal is for users to capture the rtsp stream from an indoor panel ..
Some users sont have access to the outdoor station, providing the stream, .. but they do have access to indoor station, that station does have LAN and WiFi...

So if we access it from wifi, then use the SDK to grab the rtsp from outdoor...

**Comment by surfzoid** [comment]
Hi, i suggest to you, have a look at my project #QtVsplayer, you will find an more recent sdk , i got it directly from Hikvision, through hik partner support.
Qtvsplayer support RTSP stream with SDK

**Comment by pergolafabio** [comment]
ok, will have a look at that project... But not sure how i can/alter the config
I want to SDK to connect to like device 192.168.0.71 , but the stream should come from 192.168.0.70 ?

i also received it from Hik, this one .... HCNetSDKV6.1.8.101_build20211210_Arm_aarch64-linux
what build did you receive?

**Comment by surfzoid** [comment]
sorry i can't remembrer, install qtvsplayer and look at the console at startup

**Comment by pergolafabio** [comment]
ok, need to installl some c++ tools first, never used it before
But i tried to launch the win editrion, it doesnt play video, unless i click on "rtsp play"

**Comment by surfzoid** [comment]
Hum, why? Linux should be best, no need other things, replace library, dll or so or dylib and use the version function!
